# Generated by Django 5.2.1 on 2025-09-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owneruser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
