# Generated by Django 5.2.1 on 2025-09-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_owneruser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owneruser",
            name="business_license_image",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
