# Generated by Django 5.1.7 on 2025-08-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='session_scope',
            field=models.CharField(choices=[('guest', '게스트'), ('owner', '사장님')], db_index=True, default='guest', max_length=10),
        ),
    ]
