# Generated by Django 5.2.1 on 2025-08-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_refreshtoken_session_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("owner", "사장님"), ("guest", "게스트")], max_length=10
            ),
        ),
    ]
