FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./backend /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD bash -c "\
    echo '🔧 Running migrations...' && \
    python manage.py migrate --noinput && \
    echo '🧹 Collecting static files...' && \
    python manage.py collectstatic --noinput && \
    echo '🚀 Starting Gunicorn server...' && \
    exec gunicorn config.wsgi:application --bind 0.0.0.0:8000"
