# Generated by Django 5.1.7 on 2025-08-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='neighbiz', max_length=128),
        ),
        migrations.AddField(
            model_name='merchant',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
