# Generated by Django 5.2.1 on 2025-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0002_merchant_password_merchant_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="owner_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
