# Generated by Django 5.2.1 on 2025-09-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partnerships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnership",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
