# Generated by Django 5.2.1 on 2025-08-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partnerships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnership",
            name="slug_for_a",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="partnership",
            name="slug_for_b",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
