# Generated by Django 5.2.1 on 2025-09-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partnerships", "0002_alter_partnership_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="partnershipchangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "검토 중"),
                    ("accepted", "승낙됨"),
                    ("rejected", "거절됨"),
                    ("cancelled", "제안 취소됨"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "검토 중"),
                    ("accepted", "승낙됨"),
                    ("rejected", "거절됨"),
                    ("cancelled", "제안 취소됨"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
