# Generated by Django 5.2.1 on 2025-08-24 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partnerships", "0002_partnership_slug_for_a_partnership_slug_for_b"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnership",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partnerships.post",
            ),
        ),
        migrations.AlterField(
            model_name="partnership",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partnerships.proposal",
            ),
        ),
    ]
