# Generated by Django 5.2.1 on 2025-08-26 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_couponpolicy_expected_duration"),
        ("partnerships", "0003_alter_partnership_post_alter_partnership_proposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coupons.couponpolicy",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="offered_value",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "제휴 요청 중"),
                    ("accepted", "제휴 승낙"),
                    ("rejected", "제휴 거절"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
