# Generated by Django 5.2.1 on 2025-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_alter_store_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
