# Generated by Django 5.2.1 on 2025-09-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("expected_value", models.PositiveIntegerField()),
                (
                    "expected_duration",
                    models.CharField(
                        choices=[
                            ("1_month", "1개월"),
                            ("2_months", "2개월"),
                            ("3_months", "3개월"),
                            ("6_months", "6개월"),
                            ("unlimited", "무기한"),
                        ],
                        default="1_month",
                        max_length=20,
                    ),
                ),
                ("monthly_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_policies",
                        to="stores.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("short_code", models.CharField(max_length=12, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "사용 전"),
                            ("used", "사용 완료"),
                            ("expired", "만료됨"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="accounts.consumeruser",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="coupons.couponpolicy",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["short_code"], name="coupons_cou_short_c_5c9542_idx"
                    ),
                    models.Index(fields=["slug"], name="coupons_cou_slug_69c249_idx"),
                ],
            },
        ),
    ]
