# Generated by Django 5.2.1 on 2025-09-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expired_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="couponpolicy",
            name="expected_duration",
            field=models.CharField(
                choices=[
                    ("1_month", "1개월"),
                    ("2_months", "2개월"),
                    ("3_months", "3개월"),
                    ("6_months", "6개월"),
                    ("1_year", "1년"),
                ],
                default="1_month",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="couponpolicy",
            name="monthly_limit",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
