# Generated by Django 5.2.1 on 2025-08-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponpolicy",
            name="expected_value",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
