# Generated by Django 5.2.1 on 2025-09-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_alter_coupon_expired_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="coupon",
            name="coupons_cou_slug_69c249_idx",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="slug",
        ),
    ]
