# Generated by Django 5.2.1 on 2025-08-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_couponpolicy_expected_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponpolicy",
            name="expected_duration",
            field=models.CharField(
                choices=[
                    ("1_month", "1개월"),
                    ("3_months", "3개월"),
                    ("6_months", "6개월"),
                    ("unlimited", "무기한"),
                ],
                default="unlimited",
                max_length=20,
            ),
        ),
    ]
