# Generated by Django 5.2.1 on 2025-12-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_remove_coupon_coupons_cou_slug_69c249_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="partnership_slug",
            field=models.CharField(db_index=True, default="6a8695ddd5", max_length=32),
            preserve_default=False,
        ),
    ]
