# Generated by Django 5.2.1 on 2025-09-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_couponpolicy_expected_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couponpolicy",
            name="valid_from",
        ),
        migrations.RemoveField(
            model_name="couponpolicy",
            name="valid_until",
        ),
    ]
